### ISSUE TITLE
Text not sending in Lite version

### ISSUE THREAD

**Issue by untalkatively** [Brismuth-Apps-LLC/bulk-texter-lite#241]
**Did the issue suddenly begin happening, or is this your first time using Bulk Texter Lite?**
It's the first time I'm using it.

**Describe the bug**
The app enters the phone number, but it does not enter the message and send it. I tried this with and without personalization. I was sending a text to just one number, my cell phone, to test out the app.

**Screenshots**

![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/161361310/3b4445ed-c559-4812-ae56-03f356fabdfd)

**Comment by lmstone** [comment]
I am having this same issue as well. Can someone help me?

**Comment by mixedcomusic** [comment]
I've just started experiencing this issue/error as well.  I've been using it on a bi-monthly basis, flawlessly.   Worked through the recommended updates, but no luck.

**Comment by brismuth** [comment]
I might have found the issue and resolved it with v3.0.5. v3.0.5 is now live on the Firefox add-on store, and also for manual Chrome installation. 

Can you try following these instructions to update to v3.0.5 and see if it resolves the issue?
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite?tab=readme-ov-file#update-it

**Comment by brismuth** [comment]
Actually, hold on – I see another potential issue and I'll fix that in v3.0.6.

**Comment by brismuth** [comment]
Okay, v3.0.6 is released now for manual Chrome installation and should be released for Firefox shortly, and for Edge in the next few days.

**Comment by heyikang** [comment]
v3.0.6
<img width="448" alt="image" src="https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/34233756/a7f7604a-114b-49ba-9064-0466c3291678">

**Comment by untalkatively** [comment]
I get the same error in Chrome.

![image](https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/161361310/ec555c30-660e-44e0-b7c2-b015ab80bbfa)

**Comment by brismuth** [comment]
Thanks for letting me know – I think I found the issue and corrected it in v3.0.7. v3.0.7 is released now for manual Chrome installation and for Firefox, and will be released for Edge in the next few days.

**Comment by heyikang** [comment]
Same problem
<img width="448" alt="image" src="https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/34233756/4bff1314-2c24-401a-9376-f80fcc4e7116">

**Comment by heyikang** [comment]
> Same problem <img alt="image" width="448" src="https://private-user-images.githubusercontent.com/34233756/308247593-4bff1314-2c24-401a-9376-f80fcc4e7116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTAxNjEsIm5iZiI6MTcwOTA0OTg2MSwicGF0aCI6Ii8zNDIzMzc1Ni8zMDgyNDc1OTMtNGJmZjEzMTQtMmMyNC00MDFhLTkzNzYtZjgwZmNjNGU3MTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE2MDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ODMwZWYyNWI1OTlkNGY3MjIxNGQ2YzcxNzc1M2JmMjM2NmY3ZmYyNGFjZjI5MDEwNGY3M2E3ZjdhNzE0MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eB6c81eSKSJ_FeviAVeiYceMkp8l_qIxUzS1NOFSrRU">

<img width="684" alt="image" src="https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/assets/34233756/404d4f62-0071-440d-826a-7491faed7bcb">

**Comment by brismuth** [comment]
Okay, there must be something else I’m missing. I’ll be able to look at this again tonight - in the meantime, anyone affected should try using Bulk Texter Pro:
https://www.bulktexterpro.com/

No one has reported the issue on Bulk Texter Pro yet, and there’s a free 7 day trial.

**Comment by brismuth** [comment]
Okay, thanks for your patience everyone! I think I got the last missing piece, and the issue should hopefully be resolved with Bulk Texter Lite v3.0.8, which is now released for manual Chrome installation and for Firefox, and will be released for Edge in the next few days.

**Comment by RiddemPests** [comment]
Just wanted to document the problem on edge where the first person will loop without the message sending. Thanks for the upcoming update, your app saves me SO much time running my one man pest control company. Thank you

**Comment by brismuth** [comment]
Thanks @RiddemPests – Edge typically takes 5-8 days to review extension changes on their store, while Chrome and Firefox are much faster. Unfortunately it's out of my control – it's just how they do it.

**Comment by untalkatively** [comment]
I used Bulk Tester Pro in Edge with no problems. I tested the Lite version you fixed in Chrome and it works. I'm looking forward to it rolling out in Edge. Thanks for fixing it so quickly!

**Comment by mixedcomusic** [comment]
> Okay, there must be something else I’m missing. I’ll be able to look at this again tonight - in the meantime, anyone affected should try using Bulk Texter Pro: https://www.bulktexterpro.com/
> 
> No one has reported the issue on Bulk Texter Pro yet, and there’s a free 7 day trial.

Hello!

I just upgraded to Bulk Texter Pro with an annual subscription.  With Edge, I'm still experiencing this issue.

**Comment by brismuth** [comment]
Hi @mixedcomusic - see the comment two posts above yours:
https://github.com/Brismuth-Apps-LLC/bulk-texter-lite/issues/241#issuecomment-1970358959

The reviewers for Microsoft Edge still haven’t completed review for the Bulk Texter Pro update at this point. However, your subscription will also work on Firefox and Chrome - you’ll just need to sign in with your account on either of those browsers.

**Comment by brismuth** [comment]
Actually, sorry, I just realized you’re referring to Bulk Texter Pro and not Lite. 

Can you email me at support@bulktexterpro.com? I’m not aware of this issue occurring with Bulk Texter Pro on Edge right now.

**Comment by mixedcomusic** [comment]
Hello!

Thanks for such a quick reply!  I’ve tried two things since returning to the computer – restarting my computer, and attempting to send without an attached image. 

I can’t say if one of these two things “solved” part of the issue.  I have discovered that while a text with no image is going through, attempting to send with an image is not working. 


I’ve attached a video for reference – there is a long delay between pressing “send” on the Bulk Texter Pro page and action seen on the Google Voice page (Just wanted you to be aware of the long waits in the video).   The first part is showing that a text-only message is successfully passing through (tested after the video was recorded, I found that a text-only message to a group of people is successfully going through). The second part shows me attempting to send a message with an attached image.  This fails and results in either an Edge error message (which wasn’t recorded for some reason), or the Google Voice page fully refreshed, back to normal,  like nothing happened.  In all instances, the Pending list on the Bulk Texter Pro page is clear.   

Perhaps I was just having fun earlier today while trying the attached image feature and never attempted a text-only message before making my post.  Apologies for being a bit hasty about that. 


Is there an image filetype requirement, maybe, for sending attached images in texts? 

 

All the best,

 

Dom Melanson

**Comment by brismuth** [comment]
@mixedcomusic your video did not come through to the Github discussion, but both issues you mentioned – the issue sending images and the delay before Bulk Texter Pro starts sending – are present in v2.6.0, which is what is currently on the Edge store. v2.7.1 resolves both of those issues – see the release notes here for v2.6.1 and v2.7.1:
https://www.bulktexterpro.com/docs/release-notes/

Unfortunately, the Edge review process is just extremely slow. I'd recommend using Firefox or Chrome in the meantime if you need to send images. Hopefully the Edge review for v2.7.1 will be completed this week.

**Comment by brismuth** [comment]
@mixedcomusic you can also follow these instructions to install the [Chrome web store version](https://chromewebstore.google.com/detail/bulk-texter-pro/kpjadjgajlgmkefnnihfedmcabapnndj) of Bulk Texter Pro on Edge, which should also work to get the latest version:
https://support.microsoft.com/en-us/microsoft-edge/add-turn-off-or-remove-extensions-in-microsoft-edge-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026
